# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import google_mrf_pb2 as google__mrf__pb2


class GoogleMRFStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.MRFInfo = channel.unary_unary(
        '/googlemrf.GoogleMRF/MRFInfo',
        request_serializer=google__mrf__pb2.Query.SerializeToString,
        response_deserializer=google__mrf__pb2.MRF.FromString,
        )
    self.MRFs = channel.unary_stream(
        '/googlemrf.GoogleMRF/MRFs',
        request_serializer=google__mrf__pb2.Empty.SerializeToString,
        response_deserializer=google__mrf__pb2.MRF.FromString,
        )
    self.Agencies = channel.unary_stream(
        '/googlemrf.GoogleMRF/Agencies',
        request_serializer=google__mrf__pb2.Empty.SerializeToString,
        response_deserializer=google__mrf__pb2.Single.FromString,
        )
    self.LOBs = channel.unary_stream(
        '/googlemrf.GoogleMRF/LOBs',
        request_serializer=google__mrf__pb2.Empty.SerializeToString,
        response_deserializer=google__mrf__pb2.Single.FromString,
        )
    self.Products = channel.unary_stream(
        '/googlemrf.GoogleMRF/Products',
        request_serializer=google__mrf__pb2.Empty.SerializeToString,
        response_deserializer=google__mrf__pb2.Double.FromString,
        )
    self.SubProducts = channel.unary_stream(
        '/googlemrf.GoogleMRF/SubProducts',
        request_serializer=google__mrf__pb2.Empty.SerializeToString,
        response_deserializer=google__mrf__pb2.Double.FromString,
        )
    self.Channels = channel.unary_stream(
        '/googlemrf.GoogleMRF/Channels',
        request_serializer=google__mrf__pb2.Empty.SerializeToString,
        response_deserializer=google__mrf__pb2.Single.FromString,
        )
    self.Medias = channel.unary_stream(
        '/googlemrf.GoogleMRF/Medias',
        request_serializer=google__mrf__pb2.Empty.SerializeToString,
        response_deserializer=google__mrf__pb2.Double.FromString,
        )
    self.SubMedias = channel.unary_stream(
        '/googlemrf.GoogleMRF/SubMedias',
        request_serializer=google__mrf__pb2.Empty.SerializeToString,
        response_deserializer=google__mrf__pb2.Double.FromString,
        )
    self.ValidateMRF = channel.unary_unary(
        '/googlemrf.GoogleMRF/ValidateMRF',
        request_serializer=google__mrf__pb2.Query.SerializeToString,
        response_deserializer=google__mrf__pb2.MRF.FromString,
        )
    self.ValidateAgency = channel.unary_unary(
        '/googlemrf.GoogleMRF/ValidateAgency',
        request_serializer=google__mrf__pb2.Query.SerializeToString,
        response_deserializer=google__mrf__pb2.Single.FromString,
        )
    self.ValidateChannel = channel.unary_unary(
        '/googlemrf.GoogleMRF/ValidateChannel',
        request_serializer=google__mrf__pb2.Query.SerializeToString,
        response_deserializer=google__mrf__pb2.Single.FromString,
        )
    self.ValidateLOB = channel.unary_unary(
        '/googlemrf.GoogleMRF/ValidateLOB',
        request_serializer=google__mrf__pb2.Query.SerializeToString,
        response_deserializer=google__mrf__pb2.Single.FromString,
        )
    self.ValidateMedia = channel.unary_unary(
        '/googlemrf.GoogleMRF/ValidateMedia',
        request_serializer=google__mrf__pb2.Query.SerializeToString,
        response_deserializer=google__mrf__pb2.Single.FromString,
        )
    self.ValidateProduct = channel.unary_unary(
        '/googlemrf.GoogleMRF/ValidateProduct',
        request_serializer=google__mrf__pb2.Query.SerializeToString,
        response_deserializer=google__mrf__pb2.Single.FromString,
        )
    self.ValidateSubMedia = channel.unary_unary(
        '/googlemrf.GoogleMRF/ValidateSubMedia',
        request_serializer=google__mrf__pb2.Query.SerializeToString,
        response_deserializer=google__mrf__pb2.Single.FromString,
        )
    self.ValidateSubProduct = channel.unary_unary(
        '/googlemrf.GoogleMRF/ValidateSubProduct',
        request_serializer=google__mrf__pb2.Query.SerializeToString,
        response_deserializer=google__mrf__pb2.Single.FromString,
        )
    self.LongTailMRFs = channel.unary_unary(
        '/googlemrf.GoogleMRF/LongTailMRFs',
        request_serializer=google__mrf__pb2.Empty.SerializeToString,
        response_deserializer=google__mrf__pb2.MRFList.FromString,
        )


class GoogleMRFServicer(object):
  """Interface exported by the server.
  """

  def MRFInfo(self, request, context):
    """Obtains a single MRF code and its related info.

    If it is not found an empty MRF is returned.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MRFs(self, request, context):
    """Obtains all MRF codes known.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Agencies(self, request, context):
    """Obtains all Agencies.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LOBs(self, request, context):
    """Obtains all LOBs known.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Products(self, request, context):
    """Obtains all Products known.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubProducts(self, request, context):
    """Obtains all SubProducts known.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Channels(self, request, context):
    """Obtains all Channels known.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Medias(self, request, context):
    """Obtains all Medias known.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubMedias(self, request, context):
    """Obtains all SubMedias known.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateMRF(self, request, context):
    """The following methods check to see if the
    described object exists.

    In the case of something like a product, the query
    can be provided with both the name of the product
    and the parent line of business. If the combination
    of product and LOB does not exist empty will be
    returned.

    Returns an empty instance if it is not found.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateAgency(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateChannel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateLOB(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateMedia(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateSubMedia(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateSubProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LongTailMRFs(self, request, context):
    """All 'long tail' mrfs.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GoogleMRFServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'MRFInfo': grpc.unary_unary_rpc_method_handler(
          servicer.MRFInfo,
          request_deserializer=google__mrf__pb2.Query.FromString,
          response_serializer=google__mrf__pb2.MRF.SerializeToString,
      ),
      'MRFs': grpc.unary_stream_rpc_method_handler(
          servicer.MRFs,
          request_deserializer=google__mrf__pb2.Empty.FromString,
          response_serializer=google__mrf__pb2.MRF.SerializeToString,
      ),
      'Agencies': grpc.unary_stream_rpc_method_handler(
          servicer.Agencies,
          request_deserializer=google__mrf__pb2.Empty.FromString,
          response_serializer=google__mrf__pb2.Single.SerializeToString,
      ),
      'LOBs': grpc.unary_stream_rpc_method_handler(
          servicer.LOBs,
          request_deserializer=google__mrf__pb2.Empty.FromString,
          response_serializer=google__mrf__pb2.Single.SerializeToString,
      ),
      'Products': grpc.unary_stream_rpc_method_handler(
          servicer.Products,
          request_deserializer=google__mrf__pb2.Empty.FromString,
          response_serializer=google__mrf__pb2.Double.SerializeToString,
      ),
      'SubProducts': grpc.unary_stream_rpc_method_handler(
          servicer.SubProducts,
          request_deserializer=google__mrf__pb2.Empty.FromString,
          response_serializer=google__mrf__pb2.Double.SerializeToString,
      ),
      'Channels': grpc.unary_stream_rpc_method_handler(
          servicer.Channels,
          request_deserializer=google__mrf__pb2.Empty.FromString,
          response_serializer=google__mrf__pb2.Single.SerializeToString,
      ),
      'Medias': grpc.unary_stream_rpc_method_handler(
          servicer.Medias,
          request_deserializer=google__mrf__pb2.Empty.FromString,
          response_serializer=google__mrf__pb2.Double.SerializeToString,
      ),
      'SubMedias': grpc.unary_stream_rpc_method_handler(
          servicer.SubMedias,
          request_deserializer=google__mrf__pb2.Empty.FromString,
          response_serializer=google__mrf__pb2.Double.SerializeToString,
      ),
      'ValidateMRF': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateMRF,
          request_deserializer=google__mrf__pb2.Query.FromString,
          response_serializer=google__mrf__pb2.MRF.SerializeToString,
      ),
      'ValidateAgency': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateAgency,
          request_deserializer=google__mrf__pb2.Query.FromString,
          response_serializer=google__mrf__pb2.Single.SerializeToString,
      ),
      'ValidateChannel': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateChannel,
          request_deserializer=google__mrf__pb2.Query.FromString,
          response_serializer=google__mrf__pb2.Single.SerializeToString,
      ),
      'ValidateLOB': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateLOB,
          request_deserializer=google__mrf__pb2.Query.FromString,
          response_serializer=google__mrf__pb2.Single.SerializeToString,
      ),
      'ValidateMedia': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateMedia,
          request_deserializer=google__mrf__pb2.Query.FromString,
          response_serializer=google__mrf__pb2.Single.SerializeToString,
      ),
      'ValidateProduct': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateProduct,
          request_deserializer=google__mrf__pb2.Query.FromString,
          response_serializer=google__mrf__pb2.Single.SerializeToString,
      ),
      'ValidateSubMedia': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateSubMedia,
          request_deserializer=google__mrf__pb2.Query.FromString,
          response_serializer=google__mrf__pb2.Single.SerializeToString,
      ),
      'ValidateSubProduct': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateSubProduct,
          request_deserializer=google__mrf__pb2.Query.FromString,
          response_serializer=google__mrf__pb2.Single.SerializeToString,
      ),
      'LongTailMRFs': grpc.unary_unary_rpc_method_handler(
          servicer.LongTailMRFs,
          request_deserializer=google__mrf__pb2.Empty.FromString,
          response_serializer=google__mrf__pb2.MRFList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'googlemrf.GoogleMRF', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
